/tigress/ruairidh/model_results
entering python script
[2018/09/21 15:20:45 __main__ INFO] - {
  "model_config": {
    "arch": "vgg",
    "input_shape": [
      1,
      3,
      32,
      32
    ],
    "n_classes": 10,
    "n_channels": [
      64,
      128,
      256,
      512,
      512
    ],
    "n_layers": [
      2,
      2,
      3,
      3,
      3
    ],
    "use_bn": true
  },
  "optim_config": {
    "epochs": 160,
    "batch_size": 128,
    "optimizer": "sgd",
    "base_lr": 0.1,
    "weight_decay": 0.0001,
    "momentum": 0.9,
    "nesterov": true,
    "scheduler": "multistep",
    "milestones": [
      80,
      120
    ],
    "lr_decay": 0.1
  },
  "data_config": {
    "dataset": "CIFAR10",
    "n_classes": 10,
    "num_workers": 7,
    "batch_size": 128,
    "use_cutout": false,
    "use_random_erasing": false,
    "use_mixup": false,
    "use_gpu": true
  },
  "run_config": {
    "outdir": "/tigress/ruairidh/model_results/vgg_15_BN_64",
    "seed": 7,
    "test_first": true,
    "gpu": "0",
    "tensorboard": false,
    "tensorboard_train_images": false,
    "tensorboard_test_images": false,
    "tensorboard_model_params": false,
    "use_gpu": true
  },
  "env_info": {
    "pytorch_version": "0.4.1",
    "cuda_version": "9.2.148",
    "cudnn_version": 7104,
    "gpu0": {
      "name": "Tesla P100-PCIE-16GB",
      "capability": "6.0"
    }
  }
}
Files already downloaded and verified
Files already downloaded and verified
[2018/09/21 15:20:47 __main__ INFO] - Loading model...
[2018/09/21 15:20:47 __main__ INFO] - n_params: 14728266
[2018/09/21 15:20:49 __main__ INFO] - Done
/home/ruairidh/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
[2018/09/21 15:20:49 __main__ INFO] - Test 0
[2018/09/21 15:20:52 __main__ INFO] - Epoch 0 Loss 2.3026 Accuracy 0.1001
[2018/09/21 15:20:52 __main__ INFO] - Elapsed 2.95
[2018/09/21 15:20:52 __main__ INFO] - Train 1
[2018/09/21 15:20:54 __main__ INFO] - Epoch 1 Step 0/390 Loss 2.3366 (2.3366) Accuracy 0.1172 (0.1172)
[2018/09/21 15:20:58 __main__ INFO] - Epoch 1 Step 100/390 Loss 1.9742 (2.1635) Accuracy 0.2500 (0.2213)
[2018/09/21 15:21:02 __main__ INFO] - Epoch 1 Step 200/390 Loss 1.6169 (1.9513) Accuracy 0.3750 (0.2759)
[2018/09/21 15:21:06 __main__ INFO] - Epoch 1 Step 300/390 Loss 1.4651 (1.8294) Accuracy 0.4375 (0.3178)
[2018/09/21 15:21:10 __main__ INFO] - Elapsed 17.68
[2018/09/21 15:21:10 __main__ INFO] - Test 1
[2018/09/21 15:21:13 __main__ INFO] - Epoch 1 Loss 1.4706 Accuracy 0.4501
[2018/09/21 15:21:13 __main__ INFO] - Elapsed 2.64
Traceback (most recent call last):
  File "./main.py", line 392, in <module>
    main()
  File "./main.py", line 384, in main
    save_checkpoint(state, outdir)
TypeError: save_checkpoint() missing 1 required positional argument: 'outdir'
done
