entering python script
[2018/09/21 15:16:17 __main__ INFO] - {
  "model_config": {
    "arch": "vgg",
    "input_shape": [
      1,
      3,
      32,
      32
    ],
    "n_classes": 10,
    "n_channels": [
      64,
      128,
      256,
      512,
      512
    ],
    "n_layers": [
      2,
      2,
      3,
      3,
      3
    ],
    "use_bn": true
  },
  "optim_config": {
    "epochs": 160,
    "batch_size": 128,
    "optimizer": "sgd",
    "base_lr": 0.1,
    "weight_decay": 0.0001,
    "momentum": 0.9,
    "nesterov": true,
    "scheduler": "multistep",
    "milestones": [
      80,
      120
    ],
    "lr_decay": 0.1
  },
  "data_config": {
    "dataset": "CIFAR10",
    "n_classes": 10,
    "num_workers": 7,
    "batch_size": 128,
    "use_cutout": false,
    "use_random_erasing": false,
    "use_mixup": false,
    "use_gpu": true
  },
  "run_config": {
    "outdir": "/tigress/ruairidh/model_results",
    "seed": 7,
    "test_first": true,
    "gpu": "0",
    "tensorboard": false,
    "tensorboard_train_images": false,
    "tensorboard_test_images": false,
    "tensorboard_model_params": false,
    "use_gpu": true
  },
  "env_info": {
    "pytorch_version": "0.4.1",
    "cuda_version": "9.2.148",
    "cudnn_version": 7104,
    "gpu0": {
      "name": "Tesla P100-PCIE-16GB",
      "capability": "6.0"
    }
  }
}
Files already downloaded and verified
Files already downloaded and verified
[2018/09/21 15:16:19 __main__ INFO] - Loading model...
[2018/09/21 15:16:19 __main__ INFO] - n_params: 14728266
[2018/09/21 15:16:21 __main__ INFO] - Done
/home/ruairidh/miniconda3/envs/pytorch_env/lib/python3.7/site-packages/torch/nn/functional.py:52: UserWarning: size_average and reduce args will be deprecated, please use reduction='elementwise_mean' instead.
  warnings.warn(warning.format(ret))
[2018/09/21 15:16:21 __main__ INFO] - Test 0
[2018/09/21 15:16:24 __main__ INFO] - Epoch 0 Loss 2.3026 Accuracy 0.1001
[2018/09/21 15:16:24 __main__ INFO] - Elapsed 3.04
[2018/09/21 15:16:24 __main__ INFO] - Train 1
[2018/09/21 15:16:25 __main__ INFO] - Epoch 1 Step 0/390 Loss 2.3366 (2.3366) Accuracy 0.1172 (0.1172)
[2018/09/21 15:16:30 __main__ INFO] - Epoch 1 Step 100/390 Loss 1.8408 (2.1443) Accuracy 0.2266 (0.2372)
[2018/09/21 15:16:34 __main__ INFO] - Epoch 1 Step 200/390 Loss 1.5477 (1.9295) Accuracy 0.3672 (0.2903)
[2018/09/21 15:16:38 __main__ INFO] - Epoch 1 Step 300/390 Loss 1.4548 (1.8103) Accuracy 0.3984 (0.3286)
[2018/09/21 15:16:42 __main__ INFO] - Elapsed 17.58
[2018/09/21 15:16:42 __main__ INFO] - Test 1
[2018/09/21 15:16:45 __main__ INFO] - Epoch 1 Loss 1.4798 Accuracy 0.4607
[2018/09/21 15:16:45 __main__ INFO] - Elapsed 2.63
Traceback (most recent call last):
  File "./main.py", line 393, in <module>
    main()
  File "./main.py", line 384, in main
    save_checkpoint(state, outdir)
TypeError: save_checkpoint() missing 1 required positional argument: 'outdir'
done
